name: Compile course
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install -E ghp-compiled
    - name: Compile the course
      run: |
        poetry run python -m naucse_render compile _compiled \
            --edit-repo-url https://github.com/${{ github.repository }} \
            --edit-repo-branch main
    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Create compiled branch if not existent
      run: |
        if git fetch origin compiled; then
           echo "Branch exist: compiled"
         else
            git branch compiled
            git push origin compiled
        fi
    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Publish compiled course
      run: |
        git fetch origin compiled
        poetry run python -m ghp_import -m "Compiled" -b compiled --push _compiled/
        curl -H 'Content-Type: application/json' \
            --data '{"repository": "https://github.com/${{ github.repository }}", "branch": "compiled"}' \
            https://hooks.nauc.se/trigger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: ghp_import
        GIT_COMMITTER_NAME: ghp_import
        EMAIL: none@invalid
